#!/usr/bin/env python3
"""Generate standalone Open WebUI plugin files from the shared implementation."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "openwebui_honcho"
OUTPUT = ROOT / "dist"
PLUGINS = {
    "filter_plugin.py": ("honcho_memory.py", "class Filter:"),
    "tools_plugin.py": ("honcho_memory_tools.py", "class Tools:"),
    "actions_plugin.py": ("honcho_memory_actions.py", "class Action:"),
}


def metadata_docstring(source: str) -> str:
    start = source.index('"""')
    end = source.index('"""', start + 3) + 3
    return source[start:end]


def plugin_imports(source: str, class_marker: str) -> str:
    prefix = source[: source.index(class_marker)]
    lines = [
        line
        for line in prefix.splitlines()
        if not line.startswith('"""')
        and not line.startswith("title:")
        and not line.startswith("description:")
        and not line.startswith("required_open_webui_version:")
        and not line.startswith("requirements:")
        and not line.startswith("version:")
        and not line.startswith("license:")
        and line.strip() != "from openwebui_honcho.core import *"
    ]
    return "\n".join(lines).strip()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when generated artifacts differ without writing them.",
    )
    args = parser.parse_args()
    core = (PACKAGE / "core.py").read_text()
    OUTPUT.mkdir(exist_ok=True)
    stale: list[str] = []
    for source_name, (output_name, class_marker) in PLUGINS.items():
        source = (PACKAGE / source_name).read_text()
        class_body = source[source.index(class_marker) :]
        generated = "\n\n".join(
            [
                metadata_docstring(source),
                "# Generated by scripts/generate_plugins.py. Do not edit directly.",
                plugin_imports(source, class_marker),
                core,
                class_body,
            ]
        )
        output = OUTPUT / output_name
        expected = generated.rstrip() + "\n"
        if args.check:
            if not output.exists() or output.read_text() != expected:
                stale.append(output_name)
        else:
            output.write_text(expected)
    if stale:
        raise SystemExit(f"Generated plugins are stale: {', '.join(stale)}")


if __name__ == "__main__":
    main()
